## Importing modules in Python
We can import whatever module we like in python through Anaconda.

In [2]:
import math
math.sqrt(10)

3.1622776601683795

In [3]:
import math as m
m.sqrt(8)

2.8284271247461903

In [4]:
math.sqrt(1)

1.0

## Numpy
Python's module for homogeneous arrays

In [5]:
import numpy as np
# How to create numpy arrays:
l = [1,2,3]
np.array(l)

array([1, 2, 3])

In [6]:
# It converts every elememt into a single data type
l = [1,2,"hello"]
np.array(l)

array(['1', '2', 'hello'], dtype='<U11')

In [7]:
#Numpy has a lot of helper functions:
print(np.zeros(10))
print(np.ones(6))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [8]:
a = np.zeros(14,int)
a[0] = "10" # Converts string to int before assigning the value
print(a.dtype)
print (a)

int32
[10  0  0  0  0  0  0  0  0  0  0  0  0  0]


In [9]:
# N-D arrays:
print(np.zeros((2,3)))
print(np.zeros((2,3,4)))
# Passing tuples as arguments

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
# We can access data normally:
print(a[0])
a[2:6]

10


array([0, 0, 0, 0])

In [11]:
#Shape of an array
a.shape

(14,)

In [12]:
b = np.array([[10,20,30],[31,2,42],[10,20,30],[31,2,42],[10,20,30],[31,2,42]])
print(b[0])
print(b[1,0:2])
print(b[2:5, 1:2]) #can customly access every dimension
print(b.shape)

[10 20 30]
[31  2]
[[20]
 [ 2]
 [20]]
(6, 3)


# Numpy Operators
Operations on Numpy

In [19]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a + 2) # Adds 2 to every element of the array
print(a + b)
print(a * 2)
print(a * b)
print(a ** 2)
print(a ** b)

[3 4 5]
[ 6  8 10]
[2 4 6]
[ 5 12 21]
[1 4 9]
[   1   64 2187]


In [21]:
print(a.mean())
print(a.sum())

2.0
6


In [22]:
d = ((a - b) ** 2).sum()
import math as m
m.sqrt(d)

6.928203230275509